In [3]:
import pandas as pd
pd.set_option("display.max_rows", None)
fp_df = pd.read_csv('../data/interim/organized_csv_files/2018_Monaco_FP1_organized.csv')
fp_df.head()

,session_key,driver_number,lap_count,lap_mean,lap_std,lap_best,lap_median,air_temp_mean,air_temp_min,air_temp_max,...,sc_duration_in_seconds,not_green_duration_in_seconds,total_duration_in_seconds,disruption_ratio,unnamed:_0,grand_prix,date,session_type,country_code,country_name
0,984,2,37.0,84.639000,11.127724,74.291,84.3170,21.703,21.0,23.0,...,0.0,192.747,2549.397,0.075605,0,Monaco Grand Prix,2018-05-24 11:00:00,Practice_1,MON,Monaco
1,984,3,36.0,83.398500,10.788432,72.126,83.9735,21.703,21.0,23.0,...,0.0,192.747,2549.397,0.075605,0,Monaco Grand Prix,2018-05-24 11:00:00,Practice_1,MON,Monaco
2,984,5,40.0,83.616972,13.298173,73.041,78.6805,21.703,21.0,23.0,...,0.0,192.747,2549.397,0.075605,0,Monaco Grand Prix,2018-05-24 11:00:00,Practice_1,MON,Monaco
3,984,7,38.0,87.363029,17.567303,73.066,81.3560,21.703,21.0,23.0,...,0.0,192.747,2549.397,0.075605,0,Monaco Grand Prix,2018-05-24 11:00:00,Practice_1,MON,Monaco
4,984,8,24.0,81.215619,10.908473,73.943,78.8580,21.703,21.0,23.0,...,0.0,192.747,2549.397,0.075605,0,Monaco Grand Prix,2018-05-24 11:00:00,Practice_1,MON,Monaco

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)
quali_df = pd.read_csv('../data/interim/organized_csv_files/2018_Monaco_Q_organized.csv')
quali_df.head()

,session_key,driver_number,lap_count,lap_mean,lap_std,lap_best,lap_median,air_temp_mean,air_temp_min,air_temp_max,...,sc_duration_in_seconds,not_green_duration_in_seconds,total_duration_in_seconds,disruption_ratio,unnamed:_0,grand_prix,date,session_type,country_code,country_name
0,984,2,19.0,86.807600,13.766189,72.440,94.3290,26.608955,25.6,27.5,...,0.0,88.88,3502.66,0.025375,0,Monaco Grand Prix,2018-05-26 15:00:00,Qualifying,MON,Monaco
1,984,3,17.0,82.880000,13.444456,70.810,79.2795,26.608955,25.6,27.5,...,0.0,88.88,3502.66,0.025375,0,Monaco Grand Prix,2018-05-26 15:00:00,Qualifying,MON,Monaco
2,984,5,21.0,86.576625,14.122381,71.039,86.6375,26.608955,25.6,27.5,...,0.0,88.88,3502.66,0.025375,0,Monaco Grand Prix,2018-05-26 15:00:00,Qualifying,MON,Monaco
3,984,7,22.0,81.858588,9.713713,71.266,84.6560,26.608955,25.6,27.5,...,0.0,88.88,3502.66,0.025375,0,Monaco Grand Prix,2018-05-26 15:00:00,Qualifying,MON,Monaco
4,984,8,21.0,86.038706,13.009265,72.728,91.6350,26.608955,25.6,27.5,...,0.0,88.88,3502.66,0.025375,0,Monaco Grand Prix,2018-05-26 15:00:00,Qualifying,MON,Monaco

## <font color='magenta'>Need to convert q1, q2, q3 to numeric type</font>
## <font color='magenta'>Need to indicate if driver advanced to next session</font>
## <font color='magenta'>Calculate best qualifying lap for each driver per event</font>
## <font color='magenta'>Calculate delta to pole to better engage performance on track</font>
## <font color='magenta'>Calculate percentage to pole</font>

In [2]:
race_df = pd.read_csv('../data/interim/organized_csv_files/2018_Monaco_R_organized.csv')
race_df.head()

,session_key,driver_number,lap_count,lap_mean,lap_std,lap_best,lap_median,air_temp_mean,air_temp_min,air_temp_max,...,sc_duration_in_seconds,not_green_duration_in_seconds,total_duration_in_seconds,disruption_ratio,unnamed:_0,grand_prix,date,session_type,country_code,country_name
0,984,2,77.0,80.195312,5.483394,76.864,79.2780,26.640708,25.3,27.6,...,0.0,310.458,5768.097,0.053823,0,Monaco Grand Prix,2018-05-27 15:10:00,Race,MON,Monaco
1,984,3,78.0,79.164192,3.844329,75.562,78.4070,26.640708,25.3,27.6,...,0.0,310.458,5768.097,0.053823,0,Monaco Grand Prix,2018-05-27 15:10:00,Race,MON,Monaco
2,984,5,78.0,79.258244,4.060528,76.065,78.4485,26.640708,25.3,27.6,...,0.0,310.458,5768.097,0.053823,0,Monaco Grand Prix,2018-05-27 15:10:00,Race,MON,Monaco
3,984,7,78.0,79.396590,3.768781,76.392,78.8950,26.640708,25.3,27.6,...,0.0,310.458,5768.097,0.053823,0,Monaco Grand Prix,2018-05-27 15:10:00,Race,MON,Monaco
4,984,8,77.0,80.585065,5.207991,74.822,79.3520,26.640708,25.3,27.6,...,0.0,310.458,5768.097,0.053823,0,Monaco Grand Prix,2018-05-27 15:10:00,Race,MON,Monaco

## <font color='teal'>Race result got jumbled due to merging dataframes but the actual position at the checkered flag is noted int he position column.</font>
## <font color='magenta'>Use status to indicate DNF and lapped drivers. </font>
## <font color='yellow'>is_dnf&nbsp;&nbsp;&nbsp;&nbsp;laps_down</font>
## <font color='cyan'>true&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2</font>
## <font color='magenta'>Need a new column for 'started_from_pit_lane'</font>

## <font color='magenta'>Before concatenating individual files into a master file add columns 'year' 'event_id' 'row_id'</font>
## <font color='yellow'>year&nbsp;&nbsp;&nbsp;&nbsp;event_id&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;row_id</font>
## <font color='cyan'>2018&nbsp;&nbsp;2018_Monaco_Grand_Prix&nbsp;&nbsp;&nbsp;&nbsp;2018_Monaco_Grand_Prix_Qualifying_16</font>
## <font color='teal'>year&nbsp;&nbsp;&nbsp;year + event name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;year + event name + session type + driver number </font>

In [ ]:
conc_df = pd.read_csv('../data/processed/concatenated_df.csv')
conc_df.head()

,sessionkey,lap_count,lap_mean,lap_std,lap_best,lap_median,air_temp_mean,air_temp_min,air_temp_max,track_temp_mean,...,total_duration_in_seconds,disruption_ratio,grandprix,date,sessiontype,countrycode,countryname,year,event_id,row_id
0,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_2
1,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_3
2,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_5
3,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_7
4,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_8

In [27]:
conc_df.dtypes

sessionkey                          int64
lap_count                         float64
lap_mean                          float64
lap_std                           float64
lap_best                          float64
lap_median                        float64
air_temp_mean                     float64
air_temp_min                      float64
air_temp_max                      float64
track_temp_mean                   float64
track_temp_min                    float64
track_temp_max                    float64
humidity_mean                     float64
humidity_min                      float64
humidity_max                      float64
wind_speed_mean                   float64
wind_speed_min                    float64
wind_speed_max                    float64
rain_any                             bool
rain_samples_ratio                float64
rain_samples                        int64
air_temp_std                      float64
track_temp_std                    float64
humidity_std                      float64
wind_speed_std                    float64
drivernumber                        int64
abbreviation                       object
driverid                           object
teamname                           object
teamcolor                          object
teamid                             object
position                          float64
classifiedposition                 object
gridposition                      float64
q1                                 object
q2                                 object
q3                                 object
time                               object
status                             object
points                            float64
laps                              float64
yellow_count                        int64
red_count                           int64
vsc_deployed_count                  int64
sc_deployed_count                   int64
vsc_duration                       object
vsc_ending_duration                object
sc_duration                        object
not_green_duration                 object
total_duration                     object
vsc_duration_in_seconds           float64
vsc_ending_duration_in_seconds    float64
sc_duration_in_seconds            float64
not_green_duration_in_seconds     float64
total_duration_in_seconds         float64
disruption_ratio                  float64
grandprix                          object
date                               object
sessiontype                        object
countrycode                        object
countryname                        object
year                                int64
event_id                           object
row_id                             object
dtype: object

## <font color='teal'>q1, q2, q3 are not the right type (object). All other columns has the correct data type.</font>
## <font color='magenta'>Convert q1, q2, q3 to seconds.</font>
## <font color='magenta'>Create features for quali performance.</font>

In [28]:
# Check for missing values
missing_values = conc_df.isnull().sum()
print(f'*** Number of missing values: {missing_values}')
# Check for duplicates
duplicates = conc_df.duplicated().sum()
print(f"*** Number of duplicate rows: {duplicates}")

*** Number of missing values: sessionkey                           0
lap_count                            0
lap_mean                             0
lap_std                              0
lap_best                             0
lap_median                           0
air_temp_mean                        0
air_temp_min                         0
air_temp_max                         0
track_temp_mean                      0
track_temp_min                       0
track_temp_max                       0
humidity_mean                        0
humidity_min                         0
humidity_max                         0
wind_speed_mean                      0
wind_speed_min                       0
wind_speed_max                       0
rain_any                             0
rain_samples_ratio                   0
rain_samples                         0
air_temp_std                         0
track_temp_std                       0
humidity_std                         0
wind_speed_std                       0
drivernumber                         0
abbreviation                         0
driverid                            23
teamname                             0
teamcolor                            0
teamid                              23
position                          1260
classifiedposition                1680
gridposition                      1680
q1                                1686
q2                                1802
q3                                1893
time                              1909
status                            1680
points                            1680
laps                              1680
yellow_count                         0
red_count                            0
vsc_deployed_count                   0
sc_deployed_count                    0
vsc_duration                         0
vsc_ending_duration                  0
sc_duration                          0
not_green_duration                   0
total_duration                       0
vsc_duration_in_seconds              0
vsc_ending_duration_in_seconds       0
sc_duration_in_seconds               0
not_green_duration_in_seconds        0
total_duration_in_seconds            0
disruption_ratio                     0
grandprix                            0
date                                 0
sessiontype                          0
countrycode                          0
countryname                          0
year                                 0
event_id                             0
row_id                               0
dtype: int64
*** Number of duplicate rows: 0

In [29]:
# Check rows where values in driverid and teamid columns are missing
missing_rows = conc_df[conc_df['driverid'].isnull() | conc_df['teamid'].isnull()]   
print(f"*** Number of rows with missing driverid or teamid: {len(missing_rows)}")
missing_rows.head(10)

*** Number of rows with missing driverid or teamid: 23

,sessionkey,lap_count,lap_mean,lap_std,lap_best,lap_median,air_temp_mean,air_temp_min,air_temp_max,track_temp_mean,...,total_duration_in_seconds,disruption_ratio,grandprix,date,sessiontype,countrycode,countryname,year,event_id,row_id
416,983,36.0,91.965590,13.126545,78.148,86.0735,21.235052,19.5,22.4,35.305155,...,3838.730,0.141189,Spanish Grand Prix,2018-05-11 11:00:00,Practice,ESP,Spain,2018,2018_Spanish_Grand_Prix,2018_Spanish_Grand_Prix_Practice_40
615,985,38.0,84.692002,10.819718,73.302,80.5375,19.505155,18.2,20.8,33.835052,...,3913.114,0.193755,Canadian Grand Prix,2018-06-08 10:00:00,Practice,CAN,Canada,2018,2018_Canadian_Grand_Prix,2018_Canadian_Grand_Prix_Practice_34
816,987,45.0,77.612443,13.304551,64.839,72.0270,19.759596,18.4,20.8,26.814141,...,13.980,1.000000,Austrian Grand Prix,2018-06-29 11:00:00,Practice,AUT,Austria,2018,2018_Austrian_Grand_Prix,2018_Austrian_Grand_Prix_Practice_40
1014,989,36.0,89.383998,16.444916,73.525,79.4160,28.093814,27.0,29.7,41.242268,...,1712.121,0.056520,German Grand Prix,2018-07-20 11:00:00,Practice,GER,Germany,2018,2018_German_Grand_Prix,2018_German_Grand_Prix_Practice_34
1016,989,36.0,89.383998,16.444916,73.525,79.4160,28.093814,27.0,29.7,41.242268,...,1712.121,0.056520,German Grand Prix,2018-07-20 11:00:00,Practice,GER,Germany,2018,2018_German_Grand_Prix,2018_German_Grand_Prix_Practice_36
1116,990,33.0,95.471601,17.211463,77.613,86.9800,27.866327,26.2,29.3,44.673469,...,3605.884,0.065295,Hungarian Grand Prix,2018-07-27 11:00:00,Practice,HUN,Hungary,2018,2018_Hungarian_Grand_Prix,2018_Hungarian_Grand_Prix_Practice_36
1217,991,26.0,117.316767,12.383437,104.358,110.7280,15.286364,14.4,16.7,22.841818,...,6533.247,0.017932,Belgian Grand Prix,2018-08-24 11:00:00,Practice,BEL,Belgium,2018,2018_Belgian_Grand_Prix,2018_Belgian_Grand_Prix_Practice_47
1317,992,28.0,102.910211,7.866929,94.000,99.5380,18.486239,17.5,19.6,22.285321,...,2835.516,0.007735,Italian Grand Prix,2018-08-31 11:00:00,Practice,ITA,Italy,2018,2018_Italian_Grand_Prix,2018_Italian_Grand_Prix_Practice_47
1513,994,28.0,110.076898,14.412570,94.488,102.9330,22.187963,21.5,23.4,28.374074,...,4072.240,0.006289,Russian Grand Prix,2018-09-28 11:00:00,Practice,RUS,Russia,2018,2018_Russian_Grand_Prix,2018_Russian_Grand_Prix_Practice_34
1515,994,28.0,110.076898,14.412570,94.488,102.9330,22.187963,21.5,23.4,28.374074,...,4072.240,0.006289,Russian Grand Prix,2018-09-28 11:00:00,Practice,RUS,Russia,2018,2018_Russian_Grand_Prix,2018_Russian_Grand_Prix_Practice_36

In [30]:
# Check rows where values in driverid and teamid columns are missing and sessiontype isn't practice
sessiontype = conc_df['sessiontype'].astype(str).str.strip().str.lower()
missing_rows_not_practice = conc_df[(conc_df['driverid'].isnull() | conc_df['teamid'].isnull()) & (sessiontype != 'practice')] 
print(f"*** Number of rows with missing driverid or teamid: {len(missing_rows_not_practice)}")
missing_rows_not_practice.head(10)

*** Number of rows with missing driverid or teamid: 0

Empty DataFrame
Columns: [sessionkey, lap_count, lap_mean, lap_std, lap_best, lap_median, air_temp_mean, air_temp_min, air_temp_max, track_temp_mean, track_temp_min, track_temp_max, humidity_mean, humidity_min, humidity_max, wind_speed_mean, wind_speed_min, wind_speed_max, rain_any, rain_samples_ratio, rain_samples, air_temp_std, track_temp_std, humidity_std, wind_speed_std, drivernumber, abbreviation, driverid, teamname, teamcolor, teamid, position, classifiedposition, gridposition, q1, q2, q3, time, status, points, laps, yellow_count, red_count, vsc_deployed_count, sc_deployed_count, vsc_duration, vsc_ending_duration, sc_duration, not_green_duration, total_duration, vsc_duration_in_seconds, vsc_ending_duration_in_seconds, sc_duration_in_seconds, not_green_duration_in_seconds, total_duration_in_seconds, disruption_ratio, grandprix, date, sessiontype, countrycode, countryname, year, event_id, row_id]
Index: []

[0 rows x 64 columns]

## <font color='teal'>Teams allow reserve drivers or future prospects to participate in practice session. Since all missing values are from practice sessions missing driverid is justified. teamid will be filled based on teamname</font>

In [31]:
# Check for missing values in gridposition and status columns
missing_gridposition_and_status = conc_df[(conc_df['gridposition'].isnull() | conc_df['status'].isnull())]
print(f"*** Number of rows with missing gridposition or status: {len(missing_gridposition_and_status)}")
missing_gridposition_and_status.head(10)

*** Number of rows with missing gridposition or status: 1680

,sessionkey,lap_count,lap_mean,lap_std,lap_best,lap_median,air_temp_mean,air_temp_min,air_temp_max,track_temp_mean,...,total_duration_in_seconds,disruption_ratio,grandprix,date,sessiontype,countrycode,countryname,year,event_id,row_id
0,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_2
1,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_3
2,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_5
3,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_7
4,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_8
5,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_9
6,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_10
7,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_11
8,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_14
9,979,30.0,98.024185,13.532707,84.026,91.157,26.781373,25.2,28.9,42.3,...,2705.243,0.001553,Australian Grand Prix,2018-03-23 12:00:00,Practice,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Practice_16

In [32]:
# Check for missing values in gridposition and status columns where sessiontype isn't practice
sessiontype = conc_df['sessiontype'].astype(str).str.strip().str.lower()
missing_gridposition_and_status = conc_df[(conc_df['gridposition'].isnull() | conc_df['status'].isnull()) & (sessiontype != 'practice')]
print(f"*** Number of rows with missing gridposition or status: {len(missing_gridposition_and_status)}")
missing_gridposition_and_status.head(10)

*** Number of rows with missing gridposition or status: 420

,sessionkey,lap_count,lap_mean,lap_std,lap_best,lap_median,air_temp_mean,air_temp_min,air_temp_max,track_temp_mean,...,total_duration_in_seconds,disruption_ratio,grandprix,date,sessiontype,countrycode,countryname,year,event_id,row_id
60,979,20.0,97.624467,13.889489,81.164,99.638,24.737179,24.2,25.2,30.473077,...,1784.862,0.33965,Australian Grand Prix,2018-03-24 17:00:00,Qualifying,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Qualifying_44
61,979,20.0,97.624467,13.889489,81.164,99.638,24.737179,24.2,25.2,30.473077,...,1784.862,0.33965,Australian Grand Prix,2018-03-24 17:00:00,Qualifying,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Qualifying_7
62,979,20.0,97.624467,13.889489,81.164,99.638,24.737179,24.2,25.2,30.473077,...,1784.862,0.33965,Australian Grand Prix,2018-03-24 17:00:00,Qualifying,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Qualifying_5
63,979,20.0,97.624467,13.889489,81.164,99.638,24.737179,24.2,25.2,30.473077,...,1784.862,0.33965,Australian Grand Prix,2018-03-24 17:00:00,Qualifying,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Qualifying_33
64,979,20.0,97.624467,13.889489,81.164,99.638,24.737179,24.2,25.2,30.473077,...,1784.862,0.33965,Australian Grand Prix,2018-03-24 17:00:00,Qualifying,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Qualifying_3
65,979,20.0,97.624467,13.889489,81.164,99.638,24.737179,24.2,25.2,30.473077,...,1784.862,0.33965,Australian Grand Prix,2018-03-24 17:00:00,Qualifying,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Qualifying_20
66,979,20.0,97.624467,13.889489,81.164,99.638,24.737179,24.2,25.2,30.473077,...,1784.862,0.33965,Australian Grand Prix,2018-03-24 17:00:00,Qualifying,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Qualifying_8
67,979,20.0,97.624467,13.889489,81.164,99.638,24.737179,24.2,25.2,30.473077,...,1784.862,0.33965,Australian Grand Prix,2018-03-24 17:00:00,Qualifying,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Qualifying_27
68,979,20.0,97.624467,13.889489,81.164,99.638,24.737179,24.2,25.2,30.473077,...,1784.862,0.33965,Australian Grand Prix,2018-03-24 17:00:00,Qualifying,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Qualifying_55
69,979,20.0,97.624467,13.889489,81.164,99.638,24.737179,24.2,25.2,30.473077,...,1784.862,0.33965,Australian Grand Prix,2018-03-24 17:00:00,Qualifying,AUS,Australia,2018,2018_Australian_Grand_Prix,2018_Australian_Grand_Prix_Qualifying_77

In [33]:
# Check for missing values in gridposition and status columns where sessiontype isn't practice or qualifying
sessiontype = conc_df['sessiontype'].astype(str).str.strip().str.lower()
missing_gridposition_and_status = conc_df[(conc_df['gridposition'].isnull() | conc_df['status'].isnull()) & (sessiontype != 'practice') & (sessiontype != 'qualifying')]
print(f"*** Number of rows with missing gridposition or status: {len(missing_gridposition_and_status)}")
missing_gridposition_and_status.head(10)

*** Number of rows with missing gridposition or status: 0

Empty DataFrame
Columns: [sessionkey, lap_count, lap_mean, lap_std, lap_best, lap_median, air_temp_mean, air_temp_min, air_temp_max, track_temp_mean, track_temp_min, track_temp_max, humidity_mean, humidity_min, humidity_max, wind_speed_mean, wind_speed_min, wind_speed_max, rain_any, rain_samples_ratio, rain_samples, air_temp_std, track_temp_std, humidity_std, wind_speed_std, drivernumber, abbreviation, driverid, teamname, teamcolor, teamid, position, classifiedposition, gridposition, q1, q2, q3, time, status, points, laps, yellow_count, red_count, vsc_deployed_count, sc_deployed_count, vsc_duration, vsc_ending_duration, sc_duration, not_green_duration, total_duration, vsc_duration_in_seconds, vsc_ending_duration_in_seconds, sc_duration_in_seconds, not_green_duration_in_seconds, total_duration_in_seconds, disruption_ratio, grandprix, date, sessiontype, countrycode, countryname, year, event_id, row_id]
Index: []

[0 rows x 64 columns]

## <font color='teal'>Drivers may start the race from the pit lane due to poor performance in qualifying or parts change. Therefore, they have no grid position.</font>
## <font color='magenta'>Create categorical feature for pit lane start</font>